spec:
  group: cuerator.io
  names:
    plural: installations
    shortNames:
      - install
      - inst
    kind: Installation
    categories:
      - cuerator
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - image
                - versionConstraint
              properties:
                image:
                  type: string
                  description: The name of the image containing the Cuerator Collection.
                versionConstraint:
                  type: string
                  description: A semantic version constraint that determines which version of the image to use.
                inputs:
                  type: array
                  items:
                    type: object
                    required:
                      - path
                    properties:
                      path:
                        type: string
                        description: The path within the Cuerator inputs struct at which the value is merged.
                      value:
                        description: The value, expressed as a YAML value (not a CUE expression).
                        x-kubernetes-preserve-unknown-fields: true
                      valueFrom:
                        type: object
                        description: Obtain the input value from another Kubernetes resource.
                        properties:
                          configMapKeyRef:
                            type: object
                            description: Obtain the input value from a specific key of a ConfigMap.
                            required:
                              - name
                              - key
                            properties:
                              name:
                                type: string
                                description: The name of the ConfigMap.
                              key:
                                type: string
                                description: The key within the ConfigMap.
                              optional:
                                type: boolean
                                description: Indicates whether to ignore this reference if the ConfigMap or key does not exist; otherwise, an error occurs.
                          secretKeyRef:
                            type: object
                            description: Obtain the input value from a specific key of a Secret.
                            required:
                              - name
                              - key
                            properties:
                              name:
                                type: string
                                description: The name of the Secret.
                              key:
                                type: string
                                description: The key within the Secret.
                              optional:
                                type: boolean
                                description: Indicates whether to ignore this reference if the Secret or key does not exist; otherwise, an error occurs.
                        value:
                          description: The value of the input.
                        valueFrom:
                          description: Obtain the input value from another Kubernetes resource.
                          type: object
                          properties:
                            configMapKeyRef:
                              description: Obtain the input value from a specific key of a ConfigMap.
                              type: object
                              required:
                                - name
                                - key
                              properties:
                                name:
                                  description: The name of the ConfigMap.
                                  type: string
                                key:
                                  description: The key of the ConfigMap entry.
                                  type: string
                                optional:
                                  description: If true, the input value is optional. If the ConfigMap or key does not exist, the input value is not set.
                                  type: boolean
                            secretKeyRef:
                              description: Obtain the input value from a specific key of a ConfigMap.
                              type: object
                              required:
                                - name
                                - key
                              properties:
                                name:
                                  description: The name of the ConfigMap.
                                  type: string
                                key:
                                  description: The key of the ConfigMap entry.
                                  type: string
                                optional:
                                  description: If true, the input value is optional. If the ConfigMap or key does not exist, the input value is not set.
                                  type: boolean
                inputsFrom:
                  description: A list of references to Kubernetes resources that are used as inputs to the Cuerator Collection.
                  type: array
                  items:
                    type: object
                    properties:
                      path:
                        type: string
                        description: The path at which the values are placed within the Cuerator inputs, defaults to the root of the inputs struct.
                      configMapRef:
                        type: object
                        description: Obtain input values from a ConfigMap.
                        required:
                          - name
                        properties:
                          name:
                            type: string
                            description: The name of the ConfigMap.
                          optional:
                            type: boolean
                            description: Indicates whether to ignore this reference if the ConfigMap does not exist; otherwise, an error occurs.
                      secretRef:
                        type: object
                        description: Obtain input values from a Secret.
                        required:
                          - name
                        properties:
                          name:
                            type: string
                            description: The name of the Secret.
                          optional:
                            type: boolean
                            description: Indicates whether to ignore this reference if the Secret does not exist; otherwise, an error occurs.
            status:
              type: object
              properties:
                conditions:
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys:
                    - type
                  description: List of conditions that indicate the status of object.
                  type: array
                  items:
                    type: object
                    required:
                      - status
                      - type
                    properties:
                      type:
                        description: Type of the condition.
                        type: string
                      status:
                        description: Status of the condition.
                        type: string
                        enum:
                          - Unknown
                          - "True"
                          - "False"
                      reason:
                        description: A machine-readable explanation for the condition's last transition.
                        type: string
                      message:
                        description: A human-readable description that complements the reason.
                        type: string
                      observedGeneration:
                        description: The generation of the DNS-SD resource that was known to the controller when this condition was set.
                        type: integer
                        format: int64
                      lastTransitionTime:
                        description: The time at which this condition was last changed.
                        type: string
                        format: date-time
                desiredVersion:
                  description: The resolved version of the image, based on the version constraint.
                  type: object
                  required:
                    - normalized
                    - image
                    - tag
                    - digest
                  properties:
                    normalized:
                      description: The normalized semantic version.
                      type: string
                    image:
                      description: The image name that was used to resolve the version.
                      type: string
                    tag:
                      description: The name of the image tag.
                      type: string
                    digest:
                      description: The digest of the tag.
                      type: string
      additionalPrinterColumns:
        - name: Image
          description: The name of the image containing the Cuerator Collection.
          type: string
          jsonPath: .spec.image
        - name: Constraint
          description: The semantic version constraint that determines which version of the image to use.
          type: string
          jsonPath: .spec.versionConstraint
        - name: Desired Tag
          description: The name of the image tag the the version constraint resolves to.
          type: string
          jsonPath: .status.desiredVersion.tag
        - name: Age
          description: The time at which the installation was created.
          type: date
          jsonPath: .metadata.creationTimestamp
metadata:
  name: installations.cuerator.io
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
